version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    entrypoint:
      - '/bin/bash'
      - '-c'
      - '/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized'
    environment:
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=password
      # Master Realm + Admin user
      - KC_REALM_NAME=master
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      # Hostname
      - KC_HOSTNAME=keycloak.${EXTERNAL_DOMAIN:-external.test}
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_HOSTNAME_STRICT=false
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - PROXY_ADDRESS_FORWARDING=true
      # Log level
      - KC_LOG_LEVEL=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb-kc
    hostname: keycloak.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - keycloak.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"

  mariadb-kc:
    image: mariadb:10.4.13
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    hostname: mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
