version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    entrypoint:
      - '/bin/bash'
      - '-c'
      - '/container-tools/wait-for-it.sh -h mariadb-kc.${INTERNAL_DOMAIN:-internal.test} -p 3306 -t $${WAIT_TIMEOUT} -- /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized'
    environment:
      # Hostname
      - KC_HOSTNAME=${KEYCLOAK_SERVER_HOST:-sso.external.test}
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY_HEADERS=xforwarded
      - PROXY_ADDRESS_FORWARDING=true
      # Health and metrics
      - KC_HEALTH_ENABLED=false
      - KC_METRICS_ENABLED=false
      # Log level
      - KC_LOG_LEVEL=info
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=password
      # Wait Timeout for DB
      - WAIT_TIMEOUT=240
      # Master Realm + Admin user
      - KC_REALM_NAME=${KEYCLOAK_REALM:-master}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
      - KC_TRANSACTION_XA_TIMEOUT=600
      - KC_TRANSACTION_XA_TIMEOUT_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb-kc
    hostname: keycloak.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - keycloak.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"

  mariadb-kc:
    image: mariadb:10.4.13
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
# https://github.com/docker-library/mariadb/issues/261
# https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=true
    hostname: mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
