version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    entrypoint:
      - '/bin/bash'
      - '-c'
      - |
        find /simva/ext -type f -iname '*.jar' -exec cp {} /opt/keycloak/providers \; ;
        /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start --optimized --verbose
    environment:
      # Database
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb.${INTERNAL_DOMAIN:-internal.test}
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=password
      # Master Realm + Admin user
      - KC_REALM_NAME=master
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      # Hostname
      - KC_HOSTNAME=sso.${EXTERNAL_DOMAIN:-external.test}
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_HOSTNAME_STRICT=false
      # HTTP
      - KC_HTTP_ENABLED=true
      - KC_HTTP_HOST=0.0.0.0
      - HTTP_ADDRESS_FORWARDING=true
      # PROXY
      - KC_PROXY_HEADERS=xforwarded
      - PROXY_ADDRESS_FORWARDING=true
      # Log level
      - KC_LOG_LEVEL=info
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak:/scripts/keycloak/:ro
      - simva-dev:/simva
    depends_on:
      - mariadb
      - traefik
    hostname: sso.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - sso.${INTERNAL_DOMAIN:-internal.test}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sso.loadbalancer.server.port=8080"
      - "traefik.http.routers.sso.rule=Host(`sso.${EXTERNAL_DOMAIN:-external.test}`)"
      - "traefik.http.routers.sso.entrypoints=websecure"
      - "traefik.http.routers.sso.tls=true"

  mariadb:
    image: mariadb:10.11.9
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - keycloak-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    hostname: mariadb-kc.${INTERNAL_DOMAIN:-internal.test}
    networks:
      default:
        aliases:
          - mariadb-kc.${INTERNAL_DOMAIN:-internal.test}

volumes:
  simva-dev:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/simva
  keycloak-mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/keycloak/mariadb