#!/usr/bin/env bash

declare -x LIMESURVEY_SAML_PLUGIN_NAME
[[ -z "${LIMESURVEY_SAML_PLUGIN_NAME}" ]] && LIMESURVEY_SAML_PLUGIN_NAME="AuthSAML"

declare -x LIMESURVEY_SAML_PLUGIN_VERSION
[[ -z "${LIMESURVEY_SAML_PLUGIN_VERSION}" ]] && LIMESURVEY_SAML_PLUGIN_VERSION="0.1.0"

declare -x LIMESURVEY_SAML_PLUGIN_AUTH_SOURCE
[[ -z "${LIMESURVEY_SAML_PLUGIN_AUTH_SOURCE}" ]] && LIMESURVEY_SAML_PLUGIN_AUTH_SOURCE="https___sso_example_com_auth_realms_realms"

declare -x LIMESURVEY_SAML_PLUGIN_UID_MAPPING
[[ -z "${LIMESURVEY_SAML_PLUGIN_UID_MAPPING}" ]] && LIMESURVEY_SAML_PLUGIN_UID_MAPPING="uid"

true