#!/usr/bin/env bash

declare -x LIMESURVEY_DB_HOST
[[ -z "${LIMESURVEY_DB_HOST}" ]] && LIMESURVEY_DB_HOST="mysql"

declare -x LIMESURVEY_DB_USER
[[ -z "${LIMESURVEY_DB_USER}" ]] && LIMESURVEY_DB_USER="root"

declare -x LIMESURVEY_DB_PASSWORD
[[ -z "${LIMESURVEY_DB_PASSWORD}" ]] && LIMESURVEY_DB_PASSWORD=""

declare -x LIMESURVEY_DB_NAME
[[ -z "${LIMESURVEY_DB_NAME}" ]] && LIMESURVEY_DB_NAME="limesurvey"

declare -x LIMESURVEY_TABLE_PREFIX
[[ -z "${LIMESURVEY_TABLE_PREFIX}" ]] && LIMESURVEY_TABLE_PREFIX=""

declare -x LIMESURVEY_ADMIN_NAME
[[ -z "${LIMESURVEY_ADMIN_NAME}" ]] && LIMESURVEY_ADMIN_NAME="Lime Administrator"

declare -x LIMESURVEY_ADMIN_EMAIL
[[ -z "${LIMESURVEY_ADMIN_EMAIL}" ]] && LIMESURVEY_ADMIN_EMAIL="lime@lime.lime"

declare -x LIMESURVEY_ADMIN_USER
[[ -z "${LIMESURVEY_ADMIN_USER}" ]] && LIMESURVEY_ADMIN_USER=""

__file_env 'LIMESURVEY_ADMIN_PASSWORD'

declare -x LIMESURVEY_DEBUG
[[ -z "${LIMESURVEY_DEBUG}" ]] && LIMESURVEY_DEBUG="0"

declare -x LIMESURVEY_SQL_DEBUG
[[ -z "${LIMESURVEY_SQL_DEBUG}" ]] && LIMESURVEY_SQL_DEBUG="0"

declare -x MYSQL_SSL_CA
[[ -z "${MYSQL_SSL_CA}" ]] && MYSQL_SSL_CA=""

declare -x LIMESURVEY_USE_INNODB
[[ -z "${LIMESURVEY_USE_INNODB}" ]] && LIMESURVEY_USE_INNODB=""

# linking backwards-compatibility
if [ -n "${!MYSQL_ENV_MYSQL_*}" ]; then
    file_env 'LIMESURVEY_DB_USER' "${MYSQL_ENV_MYSQL_USER:-root}"
    if [ "$LIMESURVEY_DB_USER" = 'root' ]; then
        : "${LIMESURVEY_DB_PASSWORD:=${MYSQL_ENV_MYSQL_ROOT_PASSWORD}}"
    else
        : "${LIMESURVEY_DB_PASSWORD:=${MYSQL_ENV_MYSQL_PASSWORD}}"
    fi

    : "${LIMESURVEY_DB_NAME:=${MYSQL_ENV_MYSQL_DATABASE}}"
fi

true